name: zxcvbn
version: 1.0.1
description: Dart port of DropBox's zxcvbn library.
homepage: https://github.com/careapp-inc/zxcvbn-dart
repository: https://github.com/careapp-inc/zxcvbn-dart

dev_dependencies:
  test: any
environment:
  sdk: '>=3.0.0'
